const ROLES = {
  DIRECTOR: 'director',
  CONTROL_ESCOLAR: 'control_escolar',
  COORDINACION_ACADEMICA: 'coordinacion_academica',
  MAESTRO: 'maestro',
  ALUMNO: 'alumno',
};

const SUBROLES = {
  CONTROL_ESCOLAR_PREPARATORIA: 'control_escolar_preparatoria',
  PREFECTO_EN_LINEA: 'prefecto_en_linea',
};

const ADMIN_ROLES = [
  ROLES.DIRECTOR,
  ROLES.CONTROL_ESCOLAR,
  ROLES.COORDINACION_ACADEMICA,
];

const PERMISSIONS = {
  ALUMNO_DASHBOARD_READ: 'alumno.dashboard.read',
  ALUMNO_TAREAS_READ: 'alumno.tareas.read',
  ALUMNO_ENTREGAS_CREATE: 'alumno.entregas.create',
  ALUMNO_CALIFICACIONES_READ: 'alumno.calificaciones.read',
  ALUMNO_MATERIALES_READ: 'alumno.materiales.read',
  ALUMNO_PORTAFOLIO_READ: 'alumno.portafolio.read',
  ALUMNO_MERITOS_READ: 'alumno.meritos.read',
  ALUMNO_PLAN_ESTUDIO_READ: 'alumno.plan_estudio.read',
  ALUMNO_PAGOS_READ: 'alumno.pagos.read',
  ALUMNO_TRAMITES_READ: 'alumno.tramites.read',
  ALUMNO_TRAMITES_CREATE: 'alumno.tramites.create',

  MAESTRO_DASHBOARD_READ: 'maestro.dashboard.read',
  MAESTRO_GRUPOS_READ: 'maestro.grupos.read',
  MAESTRO_TAREAS_READ: 'maestro.tareas.read',
  MAESTRO_TAREAS_CREATE: 'maestro.tareas.create',
  MAESTRO_ENTREGAS_READ: 'maestro.entregas.read',
  MAESTRO_ENTREGAS_UPDATE: 'maestro.entregas.update',
  MAESTRO_MATERIALES_READ: 'maestro.materiales.read',
  MAESTRO_MATERIALES_CREATE: 'maestro.materiales.create',
  MAESTRO_PORTAFOLIOS_READ: 'maestro.portafolios.read',
  MAESTRO_CALIFICACIONES_FINALES_READ: 'maestro.calificaciones_finales.read',
  MAESTRO_ANUNCIOS_READ: 'maestro.anuncios.read',
  MAESTRO_ANUNCIOS_CREATE: 'maestro.anuncios.create',
  MAESTRO_SALAS_VIDEO_READ: 'maestro.salas_video.read',
  MAESTRO_SALAS_VIDEO_CREATE: 'maestro.salas_video.create',
  MAESTRO_ASISTENCIAS_READ: 'maestro.asistencias.read',
  MAESTRO_ASISTENCIAS_CREATE: 'maestro.asistencias.create',
  MAESTRO_APROVECHAMIENTO_READ: 'maestro.aprovechamiento.read',
  MAESTRO_JUSTIFICANTES_READ: 'maestro.justificantes.read',

  DIRECTOR_SUPERVISION_READ: 'director.supervision.read',
  DIRECTOR_FOLIOS_MANAGE: 'director.folios.manage',
  DIRECTOR_FINANCIAL_OVERRIDE: 'director.finanzas.override',
  DIRECTOR_CALIFICACIONES_EXTEMPORANEAS_AUTHORIZE: 'director.calificaciones_extemporaneas.authorize',
  DIRECTOR_AULAS_ASSIGN: 'director.aulas.assign',

  ADMIN_USUARIOS_RESUMEN_READ: 'admin.usuarios.resumen.read',
  ADMIN_USUARIOS_READ: 'admin.usuarios.read',
  ADMIN_USUARIOS_CREATE: 'admin.usuarios.create',
  ADMIN_DASHBOARD_READ: 'admin.dashboard.read',
  ADMIN_MATERIAS_READ: 'admin.materias.read',
  ADMIN_MATERIAS_CREATE: 'admin.materias.create',
  ADMIN_MATERIAS_UPDATE: 'admin.materias.update',
  ADMIN_PLANES_ESTUDIO_READ: 'admin.planes_estudio.read',
  ADMIN_PLANES_ESTUDIO_CREATE: 'admin.planes_estudio.create',
  ADMIN_PERIODOS_READ: 'admin.periodos.read',
  ADMIN_PERIODOS_CREATE: 'admin.periodos.create',
  ADMIN_CALIFICACIONES_VALIDACIONES_READ: 'admin.calificaciones_validaciones.read',
  ADMIN_CALIFICACIONES_VALIDACIONES_UPDATE: 'admin.calificaciones_validaciones.update',
  ADMIN_REPORTES_ACADEMICOS_READ: 'admin.reportes.academicos.read',
  ADMIN_REPORTES_AVANCE_GLOBAL_READ: 'admin.reportes.avance_global.read',
  ADMIN_REPORTES_FINANCIEROS_READ: 'admin.reportes.financieros.read',
  ADMIN_RESPALDO_READ: 'admin.respaldo.read',
  ADMIN_PAGOS_READ: 'admin.pagos.read',
  ADMIN_PAGOS_CREATE: 'admin.pagos.create',
  ADMIN_PAGOS_UPDATE: 'admin.pagos.update',
  ADMIN_PAGOS_VALIDAR: 'admin.pagos.validar',
  ADMIN_CONCEPTOS_PAGO_READ: 'admin.conceptos_pago.read',
  ADMIN_CONCEPTOS_PAGO_CREATE: 'admin.conceptos_pago.create',
  ADMIN_REGLAS_DESBLOQUEO_READ: 'admin.reglas_desbloqueo.read',
  ADMIN_REGLAS_DESBLOQUEO_CREATE: 'admin.reglas_desbloqueo.create',
  ADMIN_DESBLOQUEOS_MANUALES_READ: 'admin.desbloqueos_manuales.read',
  ADMIN_DESBLOQUEOS_MANUALES_CREATE: 'admin.desbloqueos_manuales.create',
  ADMIN_ALUMNO_DESBLOQUEO_READ: 'admin.alumnos_desbloqueo.read',
  ADMIN_CUENTAS_UPDATE: 'admin.cuentas.update',
  ADMIN_FOLIOS_USUARIOS_READ: 'admin.folios_usuarios.read',
  ADMIN_FOLIOS_USUARIOS_UPDATE: 'admin.folios_usuarios.update',
  ADMIN_FOLIOS_USUARIOS_RETIRE: 'admin.folios_usuarios.retire',
  ADMIN_FOLIOS_PAGOS_READ: 'admin.folios_pagos.read',
  ADMIN_FOLIOS_PAGOS_UPDATE: 'admin.folios_pagos.update',
  ADMIN_FOLIOS_PAGOS_RETIRE: 'admin.folios_pagos.retire',
  ADMIN_TRAMITES_READ: 'admin.tramites.read',
  ADMIN_TRAMITES_UPDATE: 'admin.tramites.update',
  ADMIN_ALUMNO_GRUPOS_READ: 'admin.alumno_grupos.read',
  ADMIN_ALUMNO_GRUPOS_CREATE: 'admin.alumno_grupos.create',
  ADMIN_ALUMNO_GRUPOS_DELETE: 'admin.alumno_grupos.delete',
  ADMIN_DOCENTE_GRUPOS_READ: 'admin.docente_grupos.read',
  ADMIN_DOCENTE_GRUPOS_CREATE: 'admin.docente_grupos.create',
  ADMIN_DOCENTE_GRUPOS_DELETE: 'admin.docente_grupos.delete',
  ADMIN_CARGA_HORARIA_READ: 'admin.carga_horaria.read',
  ADMIN_HORARIOS_READ: 'admin.horarios.read',
  ADMIN_HORARIOS_CREATE: 'admin.horarios.create',
  ADMIN_HORARIOS_UPDATE: 'admin.horarios.update',
  ADMIN_PROGRAMAS_EXTERNOS_READ: 'admin.programas_externos.read',
  ADMIN_PROGRAMAS_EXTERNOS_CREATE: 'admin.programas_externos.create',
  ADMIN_PROGRAMAS_EXTERNOS_UPDATE: 'admin.programas_externos.update',
  ADMIN_MERITOS_READ: 'admin.meritos.read',
  ADMIN_MERITOS_CREATE: 'admin.meritos.create',
  ADMIN_MERITOS_UPDATE: 'admin.meritos.update',
  ADMIN_REPROBADOS_READ: 'admin.reprobados.read',
  ADMIN_ACTAS_READ: 'admin.actas.read',
  ADMIN_ACTAS_CREATE: 'admin.actas.create',
  ADMIN_ACTAS_UPDATE: 'admin.actas.update',
  ADMIN_EXTRAORDINARIOS_READ: 'admin.extraordinarios.read',
  ADMIN_EXTRAORDINARIOS_CREATE: 'admin.extraordinarios.create',
  ADMIN_EXTRAORDINARIOS_UPDATE: 'admin.extraordinarios.update',
};

module.exports = {
  ROLES,
  SUBROLES,
  ADMIN_ROLES,
  PERMISSIONS,
};
